# Generated by Django 4.1.7 on 2023-10-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='home_page',
            new_name='HomePageConfig',
        ),
        migrations.AlterModelOptions(
            name='homepageconfig',
            options={},
        ),
    ]
