# Generated by Django 4.1.7 on 2023-10-17 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_homeconfig_delete_homepageconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeconfig',
            options={'verbose_name': 'Configuración de la página'},
        ),
    ]
