# Generated by Django 4.1.7 on 2023-10-17 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_homeconfig_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeconfig',
            options={'verbose_name': 'Configuración de la página', 'verbose_name_plural': 'Configuración de la página'},
        ),
    ]
