# Generated by Django 4.1.7 on 2023-10-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_homeconfig_subtitulo_homeconfig_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(default='Archivo de Tertulias de ¿Agustín García Calvo?', max_length=48)),
                ('subtitulo', models.TextField(default='Bienvenidos al Archivo de Tertulias de Agustín García Calvo', max_length=64)),
                ('texto_portada', models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam at tempor lectus. Etiam pharetra, sem a sagittis blandit, tortor odio euismod risus, eu tristique est nisi id sem. Pellentesque sodales est a diam aliquet commodo. Duis lobortis ante nec eros luctus, a lacinia dolor feugiat. Fusce sollicitudin, felis tempus placerat imperdiet, turpis lacus placerat justo, eu ullamcorper lacus metus ut felis. Aenean fringilla et tortor at rutrum. Etiam at est eget nunc accumsan sagittis in vel orci. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin quis hendrerit tortor.', max_length=1000, verbose_name='Texto de bienvenida')),
            ],
            options={
                'verbose_name': 'Configuración de la página',
                'verbose_name_plural': 'Configuración de la página',
            },
        ),
        migrations.DeleteModel(
            name='HomeConfig',
        ),
    ]
