# Generated by Django 4.1.7 on 2023-10-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_homeconfig_delete_homepageconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeconfig',
            options={'verbose_name': 'Configuración de la página web', 'verbose_name_plural': 'Configuración de la página web'},
        ),
        migrations.AlterField(
            model_name='homeconfig',
            name='subtitulo',
            field=models.CharField(default='Bienvenidos al Archivo de Tertulias de Agustín García Calvo', max_length=64),
        ),
        migrations.AlterField(
            model_name='homeconfig',
            name='titulo',
            field=models.CharField(default='Archivo de Tertulias de ¿Agustín García Calvo?', max_length=48),
        ),
    ]
