# Generated by Django 4.1.7 on 2023-03-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tertulia_doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('tertu_codigo', models.IntegerField()),
                ('subtitulo', models.CharField(max_length=30)),
                ('resumen', models.TextField()),
                ('cuerpo', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'tertulia',
                'verbose_name_plural': 'tertulias',
            },
        ),
    ]
