# Generated by Django 4.1.7 on 2023-03-30 21:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tertulia_doc',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='tertulia_doc',
            name='resumen',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
