# Generated by Django 4.1.7 on 2023-03-31 20:06

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readerapp', '0002_alter_tertulia_doc_cuerpo_alter_tertulia_doc_resumen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL amigable')),
            ],
        ),
        migrations.AlterField(
            model_name='tertulia_doc',
            name='cuerpo',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='tertulia_doc',
            name='resumen',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AddField(
            model_name='tertulia_doc',
            name='slug',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='readerapp.slug', verbose_name='URL amigable'),
        ),
    ]
