# Generated by Django 4.1.7 on 2023-04-01 14:08

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readerapp', '0003_slug_alter_tertulia_doc_cuerpo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Título')),
                ('old_cod', models.CharField(max_length=12, verbose_name='Código Viejo')),
                ('new_cod', models.DateField(verbose_name='Código Nuevo (Fecha)')),
                ('status', models.CharField(choices=[('NR', 'No revisado'), ('BR', 'Bronce'), ('PL', 'Plata'), ('OR', 'Oro')], default='NR', max_length=12, verbose_name='Estado de revisión')),
                ('abstract', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Resumen')),
                ('cuerpo', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Cuerpo')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateField(auto_now_add=True, verbose_name='Actualizado')),
                ('slug', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='readerapp.slug', verbose_name='URL amigable')),
            ],
            options={
                'verbose_name': 'tertulia',
                'verbose_name_plural': 'tertulias',
            },
        ),
    ]
