# Generated by Django 4.1.7 on 2023-04-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readerapp', '0004_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tertulia_doc',
        ),
    ]
