# Generated by Django 4.1.7 on 2023-04-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readerapp', '0005_delete_tertulia_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='new_cod',
            field=models.DateField(unique=True, verbose_name='Código Nuevo (Fecha)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='old_cod',
            field=models.CharField(max_length=12, unique=True, verbose_name='Código Viejo'),
        ),
    ]
