# Generated by Django 4.1.7 on 2023-04-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readerapp', '0006_alter_article_new_cod_alter_article_old_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('NR', 'No revisado'), ('BR', 'Bronce'), ('PL', 'Plata'), ('OR', 'Oro')], default='No revisado', max_length=12, verbose_name='Estado de revisión'),
        ),
    ]
