# Generated by Django 4.1.7 on 2023-04-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readerapp', '0007_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('NR', 'No revisada'), ('BR', 'Bronce'), ('PL', 'Plata'), ('OR', 'Oro')], default='No revisada', max_length=12, verbose_name='Estado de revisión'),
        ),
    ]
