# Generated by Django 4.1.7 on 2023-04-06 11:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readerapp', '0008_alter_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='borrame',
            field=ckeditor.fields.RichTextField(default='Bórrame', verbose_name='Borrame'),
        ),
    ]
