# Generated by Django 4.1.7 on 2023-04-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readerapp', '0009_article_borrame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='borrame',
        ),
    ]
