# Generated by Django 4.1.7 on 2023-04-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readerapp', '0011_etiqueta_article_etiquetas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='etiquetas',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='Sin etiquetas', max_length=255),
        ),
        migrations.DeleteModel(
            name='Etiqueta',
        ),
    ]
