# Generated by Django 4.1.7 on 2023-04-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readerapp', '0012_category_remove_article_etiquetas_article_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(default='Sin etiquetas', max_length=255, verbose_name='Etiquetas'),
        ),
    ]
