# Generated by Django 4.1.7 on 2023-04-08 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readerapp', '0013_alter_article_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Etiqueta', 'verbose_name_plural': 'Etiquetas'},
        ),
    ]
