# Generated by Django 4.1.7 on 2023-04-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readerapp', '0014_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(default='Sin etiquetas', to='readerapp.category', verbose_name='Etiquetas'),
        ),
    ]
