# Generated by Django 4.1.7 on 2023-10-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readerapp', '0018_alter_article_old_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='old_cod',
            field=models.IntegerField(unique=True, verbose_name='Código Viejo'),
        ),
    ]
