# Generated by Django 4.1.7 on 2023-10-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readerapp', '0019_alter_article_old_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='transcriber',
            field=models.CharField(max_length=255, null=True, verbose_name='Trascriptor'),
        ),
        migrations.AddField(
            model_name='article',
            name='transcrip_info',
            field=models.TextField(default='Texto de origen: [digital/papel]. Otras: [...]', verbose_name='Notas'),
        ),
    ]
