# Generated by Django 4.1.7 on 2023-10-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readerapp', '0020_article_transcriber_article_transcrip_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='revision_log',
            field=models.TextField(default='Autor (acciones); Fecha (dd/mm/aaaa)', null=True, verbose_name='Historial de revisiones'),
        ),
        migrations.AlterField(
            model_name='article',
            name='transcrip_info',
            field=models.TextField(default='Digital/Papel, otras observaciones', verbose_name='Texto origen'),
        ),
    ]
