# Generated by Django 4.1.7 on 2023-10-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readerapp', '0021_article_revision_log_alter_article_transcrip_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=34, verbose_name='Título'),
        ),
    ]
