# Generated by Django 4.1.7 on 2023-10-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readerapp', '0022_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='recording_info',
            field=models.TextField(null=True, verbose_name='Información sobre la grabación'),
        ),
    ]
