# Generated by Django 4.1.7 on 2023-10-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readerapp', '0023_article_recording_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='recording_info',
            field=models.TextField(blank=True, null=True, verbose_name='Información sobre la grabación'),
        ),
        migrations.AlterField(
            model_name='article',
            name='revision_log',
            field=models.TextField(blank=True, default='Autor (acciones); Fecha (dd/mm/aaaa)', verbose_name='Historial de revisiones'),
        ),
        migrations.AlterField(
            model_name='article',
            name='transcriber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Trascriptor'),
        ),
        migrations.AlterField(
            model_name='article',
            name='transcrip_info',
            field=models.TextField(blank=True, default='Digital/Papel, otras observaciones', verbose_name='Texto origen'),
        ),
    ]
