# Generated by Django 4.1.7 on 2023-10-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readerapp', '0024_alter_article_recording_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
