# Generated by Django 4.1.7 on 2023-10-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readerapp', '0025_article_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sources_state',
            field=models.CharField(choices=[('C', 'Completa'), ('I', 'Incompleta')], default='Incompleta', max_length=10, verbose_name='Información sobre las fuentes'),
        ),
        migrations.AlterField(
            model_name='article',
            name='transcrip_info',
            field=models.TextField(blank=True, default='Digital/Papel, otras observaciones', verbose_name='Formato del texto original'),
        ),
    ]
