# Generated by Django 4.1.7 on 2023-10-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readerapp', '0026_article_sources_state_alter_article_transcrip_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='new_cod',
            field=models.DateField(unique=True, verbose_name='Referencia (Fecha)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='old_cod',
            field=models.IntegerField(unique=True, verbose_name='Referencia vieja'),
        ),
    ]
