# Generated by Django 4.1.7 on 2023-10-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readerapp', '0027_alter_article_new_cod_alter_article_old_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sources_state',
            field=models.CharField(choices=[('I', 'Incompleta'), ('C', 'Completa')], default='Incompleta', max_length=10, verbose_name='Información sobre las fuentes'),
        ),
    ]
