# Generated by Django 4.1.7 on 2023-10-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readerapp', '0028_alter_article_sources_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, default='Sin etiquetas', to='readerapp.category', verbose_name='Etiquetas'),
        ),
    ]
