# Generated by Django 4.1.7 on 2023-10-10 10:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readerapp', '0029_alter_article_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Resumen'),
        ),
    ]
