# Generated by Django 4.1.7 on 2023-10-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readerapp', '0030_alter_article_abstract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='sources_state',
        ),
    ]
