# Generated by Django 4.1.7 on 2023-10-11 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readerapp', '0031_remove_article_sources_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='readerapp.slug', verbose_name='URL amigable'),
        ),
    ]
