# Generated by Django 4.1.7 on 2023-10-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readerapp', '0032_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='old_cod',
            field=models.IntegerField(unique=True, verbose_name='Referencia antigua'),
        ),
    ]
