# Generated by Django 4.1.7 on 2023-10-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readerapp', '0033_alter_article_old_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='transcrip_info',
            field=models.TextField(blank=True, help_text='Digital/Papel, otras observaciones', verbose_name='Formato del texto original'),
        ),
    ]
