# Generated by Django 4.1.7 on 2023-10-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readerapp', '0034_alter_article_transcrip_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='old_cod',
            field=models.IntegerField(blank=True, help_text='Dejar en blanco en caso de no tener número de referencia antigua.', null=True, unique=True, verbose_name='Referencia antigua'),
        ),
    ]
